### ISSUE TITLE
Polymorph & Grounding Totem

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/TrinityCore#38]
**Description:**

Casting polymorph on a shaman redirects it properly to the grounding totem, but the grounding totem turns into an actual sheep and starts walking around instead of just "eating it" and then dissapearing.

**Current behaviour:**

Grounding Totem turns into a sheep.

**Expected behaviour:**

Should just eat the polymorph and dissapear.

**Steps to reproduce the problem:**

    Cast grounding totem as shaman.
    Cast polymorph on shaman.

**Comment by Nawakland** [comment]
Grounding Totem doesn't work as expected with fear spell too. Same behaviour.

I track the event processor and all seems to work fine from that side.

1. Do you know if there a NPC FLAG somewhere that prevent creature to be killed if still has health point ? Cause totem is acting like creature with only 5 hp and only damage spell can kill grounding totem.
2. Where object/creature are removed from world ?

**Comment by Interstellar-dev** [comment]
Grounding Totem doesn't work as expected with fear spell too. Same behaviour.

I track the event processor and all seems to work fine from that side.

1. Do you know if there a NPC FLAG somewhere that prevent creature to be killed if still has health point ? Cause totem is acting like creature with only 5 hp and only damage spell can kill grounding totem.
2. Where object/creature are removed from world ?
