### ISSUE TITLE
Guard System - Bounty $100

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/TrinityCore#47]
Essentially, implement a guard system. It's laughable one doesn't exist.

https://github.com/TrinityCore/TrinityCore/issues/11563
https://github.com/azerothcore/azerothcore-wotlk/issues/10571

Long term we'll mod this to be more custom but at least getting a blizzlike base is doable.

Note this is also going to require actually placing the guard post game objects as no spawns exist.

Needs better defining exactly how this should work.

**Comment by T1ti** [comment]
I would like to add, there is an areaTable flags that sets where where players guard call works 
![image](https://github.com/user-attachments/assets/a47338b4-d40a-4d46-8c30-04ae67320b34)

**Comment by Bunnyblock2** [comment]
Players Call Guards might be related to PvP combat. There are areas where guards can materialize out of thin air without a Civilian being involved I am pretty darn sure. For example if they're all dead. Do we know what expansion that flag was added in? Looks to me based on the ones around it it was probably TBC or Wrath
