### ISSUE TITLE
Location Weirdness - Bounty $50

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/TrinityCore#56]
See https://github.com/TrinityCore/TrinityCore/issues/19761
See https://github.com/chromiecraft/chromiecraft/issues/30
See https://github.com/Project-Epoch/bugtracker/issues/8145

This is an ancient issue that impacts many locations.

**Comment by nabby27** [comment]
Hi @kaytotes, I've seen that you usually create bounties for issues, maybe you're interested in using [Opire](https://app.opire.dev). You don't pay out until someone claims the bounty with a PR.

PS: I'm the co-founder, so if you need anything, feel free to contact me.

**Comment by T1ti** [comment]
explaination here https://github.com/TrinityCore/TrinityCore/issues/19761#issuecomment-2484048434

**Comment by T1ti** [comment]
Fixed, they ported a fix from TC master after I brought it up

**Comment by kaytotes** [comment]
TC fix resolves the lost rigger cove discovery but dying in Winterfall Village cave still sends you to Alterac Valley.

**Comment by kaytotes** [comment]
However this does change enough that I could hackfix Winterfall by changing its nameset to a custom one rather than using the base one. Hacky, but downgrading this.

**Comment by T1ti** [comment]
Appears to be fixed for me.
![image](https://github.com/user-attachments/assets/5a4e11a2-7317-40bf-b2ad-a218375bcca6)

Before : 
![image](https://github.com/user-attachments/assets/e0ee1630-0505-4c26-a643-a69ac408e008)

**Comment by TetraDisaster0** [comment]
Fixed by another cherry pick commit. 
https://github.com/TrinityCore/TrinityCore/issues/30455
https://github.com/TrinityCore/TrinityCore/commit/b4d6ca277aef81a49e3654a3eec131ea621da991
