### ISSUE TITLE
Persistent Area Aura's not applying correctly - Bounty $25

### ISSUE THREAD

**Issue by kaytotes** [Project-Epoch/TrinityCore#59]
See https://github.com/TrinityCore/TrinityCore/issues/29903
See https://github.com/TrinityCore/TrinityCore/issues/29605

Example spells https://www.wowhead.com/tbc/spell=1543/flare https://www.wowhead.com/wotlk/spell=13810/frost-trap-aura

**Comment by rahat2134** [comment]
Is it still on?

**Comment by Bennylavaa** [comment]
@rahat2134 seems like it seeing its still listed.
